"""empty message

Revision ID: 0633969d675e
Revises: 3dd6b929d32e
Create Date: 2020-10-10 11:11:03.252916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0633969d675e'
down_revision = '3dd6b929d32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('auction_end', sa.DateTime(), nullable=False))
    op.add_column('property', sa.Column('auction_start', sa.DateTime(), nullable=False))
    op.add_column('property', sa.Column('country', sa.String(), nullable=False))
    op.add_column('property', sa.Column('listing_type', sa.Enum('house', 'apartment', 'townhouse', 'studio', 'duplex', name='listingtype'), nullable=False))
    op.add_column('property', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('property', sa.Column('state', sa.String(), nullable=False))
    op.add_column('property', sa.Column('street', sa.String(), nullable=False))
    op.add_column('property', sa.Column('suburb', sa.String(), nullable=False))
    op.add_column('property', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('property', 'features',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('property', 'auction_id')
    op.drop_column('property', 'seller_id')
    op.drop_column('property', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('property', sa.Column('seller_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property', sa.Column('auction_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('property', 'features',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('property', 'title')
    op.drop_column('property', 'suburb')
    op.drop_column('property', 'street')
    op.drop_column('property', 'state')
    op.drop_column('property', 'owner_id')
    op.drop_column('property', 'listing_type')
    op.drop_column('property', 'country')
    op.drop_column('property', 'auction_start')
    op.drop_column('property', 'auction_end')
    # ### end Alembic commands ###
