"""create starred table

Revision ID: 2a308486176d
Revises: 33401ccc58c9
Create Date: 2020-10-17 14:35:51.664283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a308486176d'
down_revision = '33401ccc58c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starred',
                    sa.Column('listing_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f(
                        'fk_starred_listing_id_listing'), ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f(
                        'fk_starred_user_id_user'), ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('listing_id', 'user_id',
                                            name=op.f('pk_starred'))
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starred')
    # ### end Alembic commands ###
