"""update user table for google sso

Revision ID: 571ee1fe7d05
Revises: dfbf4644da96
Create Date: 2020-11-14 12:07:05.376374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571ee1fe7d05'
down_revision = 'dfbf4644da96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_id', sa.String(), nullable=True))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'google_id')
    # ### end Alembic commands ###
