"""Add auction notification fields

Revision ID: a5158b873dba
Revises: 571ee1fe7d05
Create Date: 2020-11-11 00:57:52.380525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5158b873dba'
down_revision = '571ee1fe7d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('notified_ended', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('listing', sa.Column('notified_ending', sa.Boolean(), server_default='False', nullable=False))
    op.add_column('listing', sa.Column('notified_started', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'notified_started')
    op.drop_column('listing', 'notified_ending')
    op.drop_column('listing', 'notified_ended')
    # ### end Alembic commands ###
