"""empty message

Revision ID: b1d9ef402698
Revises: 3549dc4d94e8
Create Date: 2020-10-10 20:06:12.714960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d9ef402698'
down_revision = '3549dc4d94e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('house', 'apartment', 'townhouse', 'studio', 'duplex', name='listingtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('suburb', sa.String(), nullable=False),
    sa.Column('postcode', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('num_bedrooms', sa.Integer(), nullable=False),
    sa.Column('num_bathrooms', sa.Integer(), nullable=False),
    sa.Column('num_car_spaces', sa.Integer(), nullable=False),
    sa.Column('auction_start', sa.DateTime(), nullable=False),
    sa.Column('auction_end', sa.DateTime(), nullable=False),
    sa.Column('has_ensuite', sa.Boolean(), nullable=False),
    sa.Column('has_built_in_wardrobe', sa.Boolean(), nullable=False),
    sa.Column('has_bathtub', sa.Boolean(), nullable=False),
    sa.Column('is_furnished', sa.Boolean(), nullable=False),
    sa.Column('has_open_kitchen', sa.Boolean(), nullable=False),
    sa.Column('has_separate_kitchen', sa.Boolean(), nullable=False),
    sa.Column('has_island_kitchen', sa.Boolean(), nullable=False),
    sa.Column('has_gas_stove', sa.Boolean(), nullable=False),
    sa.Column('has_electric_stove', sa.Boolean(), nullable=False),
    sa.Column('has_induction_stove', sa.Boolean(), nullable=False),
    sa.Column('has_balcony', sa.Boolean(), nullable=False),
    sa.Column('has_ocean_view', sa.Boolean(), nullable=False),
    sa.Column('has_bbq', sa.Boolean(), nullable=False),
    sa.Column('has_porch', sa.Boolean(), nullable=False),
    sa.Column('has_pool', sa.Boolean(), nullable=False),
    sa.Column('has_gym', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listing')
    # ### end Alembic commands ###
