"""add blurb to user table and add profile image table

Revision ID: c2ed5b4db5e5
Revises: 1db5c6d1805a
Create Date: 2020-10-31 13:20:53.003487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ed5b4db5e5'
down_revision = '1db5c6d1805a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_image',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('image_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_profile_image_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profile_image'))
    )
    op.add_column('user', sa.Column('blurb', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'blurb')
    op.drop_table('profile_image')
    # ### end Alembic commands ###
