"""add image table

Revision ID: c8646de63d04
Revises: dcdb80510bd0
Create Date: 2020-10-25 12:29:33.814737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8646de63d04'
down_revision = 'dcdb80510bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('fk_image_listing_id_listing'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
