"""Add price and payment details to listing

Revision ID: dcdb80510bd0
Revises: 0d6d80a398f7
Create Date: 2020-10-24 09:18:03.313344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdb80510bd0'
down_revision = '0d6d80a398f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing', sa.Column('account_name', sa.String(), nullable=False))
    op.add_column('listing', sa.Column('account_number', sa.String(), nullable=False))
    op.add_column('listing', sa.Column('bsb', sa.String(), nullable=False))
    op.add_column('listing', sa.Column('reserve_price', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing', 'reserve_price')
    op.drop_column('listing', 'bsb')
    op.drop_column('listing', 'account_number')
    op.drop_column('listing', 'account_name')
    # ### end Alembic commands ###
