"""Create interactions table

Revision ID: dfbf4644da96
Revises: 2eb333c03b34
Create Date: 2020-11-01 19:49:17.465943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbf4644da96'
down_revision = '2eb333c03b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('search', 'registration', 'star', name='interactiontype'), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('search_query', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], name=op.f('fk_interaction_listing_id_listing'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_interaction_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interaction'))
    )
    op.create_index(op.f('ix_interaction_user_id'), 'interaction', ['user_id'], unique=False)
    op.create_index(op.f('ix_interaction_timestamp'), 'interaction', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interaction_timestamp'), table_name='interaction')
    op.drop_index(op.f('ix_interaction_user_id'), table_name='interaction')
    op.drop_table('interaction')
    # ### end Alembic commands ###
